export const technicalSkills = [
  { icon: "fab fa-html5", label: "HTML5" },
  { icon: "fab fa-css3-alt", label: "CSS3" },
  { icon: "fab fa-js", label: "JavaScript" },
  { icon: "fab fa-react", label: "React.js" },
  { icon: "fab fa-node-js", label: "Node.js" },
  { icon: "fas fa-server", label: "Express.js" },
  { icon: "fas fa-database", label: "MySQL" },
  { icon: "fas fa-leaf", label: "MongoDB" },
  { icon: "fab fa-bootstrap", label: "Bootstrap" },
  { icon: "fab fa-git-alt", label: "Git & GitHub" },
  { icon: "fas fa-infinity", label: "CI/CD (GitHub Actions)" },
  { icon: "fas fa-key", label: "JWT Authentication" },
  { icon: "fas fa-vial", label: "Jest & Vitest" },
  { icon: "fas fa-paint-brush", label: "Canva" },
  { icon: "fas fa-plug", label: "REST APIs" },
  { icon: "fas fa-wand-magic-sparkles", label: "Claude AI" },
];

export const softSkills = [
  { icon: "fas fa-users", label: "Team Collaboration" },
  { icon: "fas fa-bolt", label: "Quick Learning & Adaptability" },
  { icon: "fas fa-crown", label: "Leadership & Project Ownership" },
  { icon: "fas fa-comments", label: "Effective Communication" },
];

export const education = [
  {
    year: "2023 — 2025",
    degree: "MCA — Master of Computer Applications",
    school: "Rathinam Technical Campus, Coimbatore",
    grade: "Score: 72%",
  },
  {
    year: "2020 — 2023",
    degree: "B.Sc — Computer Science",
    school: "Ayya Nadar Janaki Ammal College, Sivakasi",
    grade: "Score: 72%",
  },
  {
    year: "2018 — 2020",
    degree: "HSC — Higher Secondary Certificate",
    school: "Nadar Matriculation Higher Secondary School, Rajapalayam",
    grade: "Score: 67%",
  },
  {
    year: "2017 — 2018",
    degree: "SSLC — Secondary School Leaving Certificate",
    school:
      "Sri Vaiyapuri Vidyalaya Matric Higher Secondary School, Sankarankovil",
    grade: "Score: 73%",
  },
];

export const projects = [
  {
    img: "./assets/projectimages/sample_website.png",
    alt: "Service Company Website",
    emoji: "🏢",
    link: "https://logeshkannan-hub123.github.io/Simple-web-site/",
    external: true,
    tag: "Frontend",
    name: "Service Company Website",
    desc: "A professional multi-page service company website with modern layout and responsive design principles.",
    techs: ["HTML", "CSS", "JavaScript"],
  },
  {
    img: "./assets/projectimages/resturent.png",
    alt: "Restaurant Menu Page",
    emoji: "🍽️",
    link: "https://logeshkannan-hub123.github.io/Restaurant-Menu-Page/",
    external: true,
    tag: "Frontend",
    name: "Restaurant Menu Page",
    desc: "An appealing restaurant menu page with organized food categories and a clean, attractive interface.",
    techs: ["HTML", "CSS", "Bootstrap"],
  },
  {
    img: "./assets/projectimages/Juiceshop.png",
    alt: "Juice Shop",
    emoji: "🥤",
    link: "https://logeshkannan-hub123.github.io/juice_shop_website/",
    external: true,
    tag: "Frontend",
    name: "Juice Shop Website",
    desc: "A vibrant juice shop landing page with product showcase, responsive layout, and engaging visual design.",
    techs: ["HTML", "CSS", "JavaScript"],
  },
  {
    img: "./assets/projectimages/weathercheckapp.png",
    alt: "Weather App",
    emoji: "🌤️",
    link: "https://logeshkannan-hub123.github.io/weather-check-app/",
    external: false,
    tag: "Frontend",
    name: "Weather App",
    desc: "A real-time weather lookup app — search any city to instantly see live conditions via geocoding and forecast APIs, with graceful loading states and clear error handling for invalid cities, timeouts, and offline connections.",
    techs: [
      "React",
      "Vite",
      "Open-Meteo API",
      "Geocoding API",
      "Fetch API",
      "AbortController",
      "ESLint",
    ],
  },
  {
    img: "./assets/projectimages/moviemanager.png",
    alt: "Movie Manager App",
    emoji: "🍿",
    link: "https://frontendmovies.vercel.app",
    external: false,
    tag: "Full Stack",
    name: "Movie Manager App",
    desc: "A secure full-stack movie management app with JWT authentication and complete CRUD workflows — users sign up, log in, and add, edit, or remove movies from their personal collection through protected routes.",
    techs: [
      "React",
      "React Router",
      "Axios",
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "JWT Auth",
      "bcrypt",
      "Vite",
      "Jest",
    ],
  },
  {
    img: "./assets/projectimages/DLMS.png",
    alt: "DLMS — Developer Life Management System",
    emoji: "🗂️",
    link: "https://developer-life-management-system.vercel.app/",
    external: false,
    tag: "Full Stack",
    name: "DLMS — Developer Life Management System",
    desc: "A unified, secure productivity dashboard for developers and students — manage tasks, notes, bookmarks, study progress, and project ideas from one authenticated workspace, replacing five scattered apps with one.",
    techs: [
      "React",
      "React Router",
      "Axios",
      "Context API",
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "JWT Auth",
      "bcrypt",
      "express-validator",
      "Vitest",
      "Jest",
      "GitHub Actions CI",
    ],
  },
];

export const certificates = [
  {
    img: "./assets/certificates/IMG_wpAPI.jpg",
    alt: "WhatsApp API Chatbot Certificate",
    icon: "fab fa-whatsapp",
    title: "WhatsApp API Chatbot",
    issuer: "Chatbot Development Certification",
  },
  {
    img: "./assets/certificates/IMG_heartfull.jpg",
    alt: "International Youth Seminar Certificate",
    icon: "fas fa-globe",
    title: "International Youth Seminar",
    issuer: "Youth Leadership Program",
  },
  {
    img: "./assets/certificates/India@75Quiz.jpg",
    alt: "India @75 Quiz Contest Certificate",
    icon: "fas fa-flag",
    title: "India @75 Quiz Contest",
    issuer: "National Level Quiz Participation",
  },
  {
    img: "./assets/certificates/project_publish_certificate.png",
    alt: "Project Published Certificate",
    icon: "fas fa-trophy",
    title: "Project Published Certificate",
    issuer: "IOT project Recognition",
  },
  {
    img: "./assets/certificates/travel_and_management.jpg",
    alt: "Travel and Management Certificate",
    icon: "fas fa-plane",
    title: "Travel and Management",
    issuer: "Travel & Management Course",
  },
  {
    img: "./assets/certificates/YoungProfessional.jpg",
    alt: "TCS Career Edge Certificate",
    icon: "fas fa-star",
    title: "TCS Career Edge",
    issuer: "Young Professional Certification · TCS",
  },
];

export const navLinks = [
  { href: "#home", label: "Home" },
  { href: "#about", label: "About" },
  { href: "#skills", label: "Skills" },
  { href: "#education", label: "Education" },
  { href: "#projects", label: "Projects" },
  { href: "#certificates", label: "Certificates" },
  { href: "#contact", label: "Contact" },
];
